-- This file needs to have same structure as nvconfig.lua
-- https://github.com/NvChad/ui/blob/v3.0/lua/nvconfig.lua
-- Please read that file to know all available options :(

---@type ChadrcConfig
local M = {}

M.base46 = {
  theme = "chadracula-evondev",

  transparency = true,
  hl_override = {
    Normal = { bg = { "#0b0b0b", 1 } },
    NormalFloat = { bg = { "#0b0b0b", 1 } },
    ColorColumn = { bg = { "#0b0b0b", 1 } },
    LineNr = { bg = { "#0b0b0b", 1 } },
    CursorLine = { bg = { "#0b0b0b", 1 } },
    filter = {
      dotfiles = true, -- Делаем скрытые файлы видимыми
    },
    Comment = { italic = true, fg = { "#bd935e", 1 } },
    ["@comment"] = { italic = true, fg = { "#bd935e", 1 } },
    ["@keyword"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@operator"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@type"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@type.definition"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@variable"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@variable.builtin"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@type.builtin"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@field"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@property"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@constructor"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@constant"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@constant.builtin"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@function"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@function.builtin"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@function.macro"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@parameter"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@tag"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@tag.attribute"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@tag.delimiter"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@text"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@text.strong"] = { bold = true, fg = { "#ff9e64", 1 } },
    ["@text.emphasis"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@text.underline"] = { underline = true, fg = { "#ff9e64", 1 } },
    ["@text.strike"] = { strikethrough = true, fg = { "#ff9e64", 1 } },
    ["@text.title"] = { bold = true, fg = { "#ff9e64", 1 } },
    ["@text.literal"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@text.uri"] = { underline = true, fg = { "#ff9e64", 1 } },
    ["@text.math"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@text.reference"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@text.environment"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@text.environment.name"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@text.note"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@text.todo"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@text.warning"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@text.danger"] = { italic = true, fg = { "#ff9e64", 1 } },
    ["@text.diff.add"] = { bold = true, fg = { "#ff9e64", 1 } },
    ["@text.diff.delete"] = { bold = true, fg = { "#ff9e64", 1 } },
    ["@text.diff.header"] = { bold = true, fg = { "#ff9e64", 1 } },
    ["@text.diff.new_file"] = { bold = true, fg = { "#ff9e64", 1 } },
    ["@text.diff.old_file"] = { bold = true, fg = { "#ff9e64", 1 } },
    ["@text.diff.renamed_file"] = { bold = true, fg = { "#ff9e64", 1 } },
    Pmenu = { bg = { "#0b0b0b", 1 } },
    PmenuSel = { bg = { "#0b0b0b", 1 } },
    PmenuSbar = { bg = { "#0b0b0b", 1 } },
    PmenuThumb = { bg = { "#0b0b0b", 1 } },
    SignColumn = { bg = { "#0b0b0b", 1 } },
    VertSplit = { bg = { "#0b0b0b", 1 } },
    Visual = { bg = { "#0b0b0b", 1 } },
    VisualNOS = { bg = { "#0b0b0b", 1 } },
    WildMenu = { bg = { "#0b0b0b", 1 } },
    Folded = { bg = { "#0b0b0b", 1 } },
    FoldColumn = { bg = { "#0b0b0b", 1 } },
    CursorLineNr = { bg = { "#0b0b0b", 1 } },
    MatchParen = { bg = { "#0b0b0b", 1 } },
    NonText = { bg = { "#0b0b0b", 1 } },
    SpecialKey = { bg = { "#0b0b0b", 1 } },
    EndOfBuffer = { bg = { "#0b0b0b", 1 } },
  },
}

return M
