return {
  default_file_explore = true,
  columns = {
    "icon",
    "permissions",
    "size",
    "mtime",
  },
  view_options = {
    show_hidden = true,
    natural_order = true,
  },
  win_options = {
    wrap = false,
    signcolumn = "yes",
    cursorcolumn = false,
    foldcolumn = "0",
    spell = false,
    list = false,
    conceallevel = 3,
    concealcursor = "nvic",
  },
  keymaps = {
    ["<C-c>"] = "actions.close",
    ["<C-h>"] = "actions.parent",
    ["<C-l>"] = "actions.select",
    ["<C-v>"] = { "actions.select", opts = { vertical = true } },
    ["<C-s>"] = { "actions.select", opts = { horizontal = true } },
    ["<C-t>"] = { "actions.select", opts = { tab = true } },
    ["<C-p>"] = "actions.preview",
    ["<C-a>"] = "actions.refresh",
    ["<C-r>"] = "actions.rename",
    ["<C-d>"] = "actions.delete",
    ["<C-o>"] = "actions.open_external",
    ["<C-]>"] = "actions.cd",
    ["<C-k>"] = "actions.toggle_trash",
  },
}
